#! /home/polluticorn/anaconda3/bin/python3
# Read for figures, if none, name is figure1.svg, else it is  
# Should have pwd passed into the script

import os 
import sys
import re

################################################################################
def notifySend(string):
  os.system('notify-send "' + string + '"')

def silentExecute(cmd):
  os.system('nohup ' + cmd + ' 2> /dev/null > /dev/null &')

def silentWrap(string):
  return (string + ' 2> /dev/null > /dev/null ')

def findLargestRe(exprs):
  # Compare for biggest
  biggest = exprs[0]
  for i in range(1, len(exprs)):
    if exprs[i] > biggest:
      biggest = exprs[i]
  return biggest

def largestFigName(path):
  figure = re.compile('figure[\d]*.svg')
  result = re.findall(figure, " ".join(os.listdir(path)))
  if result == []:
      return None
  return findLargestRe(result)

def newFileName(biggestFig):
  newName = 'figure' + str(int(biggestFig.split('e')[1].split('.svg')[0]) + 1) + '.svg'
  print('newName = ', newName)


################################################################################

# Get the largest number of figure[x].svg
# Init the file with touch
# Open into inkscape in fullscreen.
# User will then edit, save and quit inkscape
# Vim should then paste that graphic into your current buffer 
#   (Can be done with `r` prefix to command and the inkscape issues silenced?)

# TODO:
# Increment the figure by 1 and make new string

def main():
    path = sys.argv[1] + '/'
    biggestName = largestFigName(path)
    if biggestName == None:
        return 1
    print('largestFigName(path) = ', biggestName)
    newFileName(biggestName)
    # fullName = path + biggestName
    # print('fullName = ', fullName)
    # print('path is: ', str(path))
    command = 'inkscape -D -z --file=yourFileName.svg --export-pdf=function.pdf --export-latex'

if __name__ == "__main__":
    main()
