#! /bin/sh --

brFile='/sys/class/backlight/intel_backlight/brightness'
value=`cat $brFile`

if [ "$1" = 'up' ]
 then
   python -c "if $value < 850: print($value + 85)" > "$brFile"
fi
if [ "$1" = 'down' ]
 then
   python -c "if $value > 85: print($value - 85)" > "$brFile"
fi

