#! /bin/sh --

# Only run the script if there's an argument
if [ -z "$1" ] 
  then
  return 1
fi

# Define(s) database to store all defined searches
database='/home/polluticorn/GitHub/configuration/defines.txt'

echo $@ >> $database

arg=$(echo $@ | sed 's/ /+/g')
chromium-browser --new-window www.google.com/search?q=define+$arg 2> /dev/null > /dev/null
