#! /bin/sh --


filename=$1
echo "--------------------------------------------------------------------------------"
echo "filename for latex2png is: $filename"
echo "--------------------------------------------------------------------------------"
echo "Compiling LaTeX to PDF..."
echo "--------------------------------------------------------------------------------"
# cd /tmp # go somewhere where we can be messy with pdflatex
# assumes you're on a mac, just add an if-statement for linux vs. mac
pdflatex -output-directory /tmp $filename  # send general output to devnull
base=$(basename $filename .tex)
echo "--------------------------------------------------------------------------------"
echo "basename is: $base"
echo "--------------------------------------------------------------------------------"
echo "Converting to png..."
echo "--------------------------------------------------------------------------------"
convert -density 300 /tmp/$base.pdf -quality 100 /tmp/$base.png 
cat /tmp/$base.png | impbcopy -
