#! /bin/sh --

# Only run the script if there's an argument
if [ -z "$1" ]
  then
  echo "No argument given."
  return 1
fi

# Make directory if non-existent else no error warning.
mkdir -p bin

fullName=$1
baseName="bin/$(echo $fullName | sed s/.c//)"
errorFile="$baseName.cerror"

# Remove the previous error file.
touch $(pwd)/$errorFile
rm $(pwd)/$errorFile

# Compile statement.
gcc -Wall -ansi -o $baseName $fullName -lm 2> $errorFile

# If it compiled, run it.
if [ -s $errorFile ] # Tests if file exists and not empty. If true = no compile.
then
  printf "\n\n" >> $(pwd)/$errorFile # Formatting
  date >> $(pwd)/$errorFile # Date/time of compiling for context
  echo "Warnings present or didn't compile.\n\n"
  cat $(pwd)/$errorFile
  return 1
else
  $(pwd)/$baseName # Run the file if no errors or warnings.
fi
