#! /bin/sh
init_vim="$HOME/.config/nvim/init.vim"
bashrc="$HOME/.bashrc"
#ith="$HOME/.config/i3/"
#ithb="$HOME/.config/i3blocks/"
vimplugins="$HOME/.vim/"
keyRemaps="$HOME/.scripts/keyRemaps"
snippets="$HOME/.config/UltiSnips"

cp    $bash_aliases .
cp    $init_vim     .
cp    $bashrc       .
cp    $keyRemaps    . 
cp -R $ith          .
cp -R $ithb         .
cp -R $vimplugins   .
cp -R $snippets     .
